<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note[
<!ELEMENT note (to+,from,heading?,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>
<note>
    <envio>sms</envio>
    <to>Mercedes</to>
    <from>José</from>
    <heading>Recordar</heading>
    <body>No olvides el cumpleaños de Andrés!</body>
</note>